### ISSUE TITLE
Pre-training error

### ISSUE THREAD

**Issue by koustav123** [ZhiGroup/Med-BERT#10]
Hi I created a toy data with 1000 patients, following the sample data provided. My cohort looks like this.
![image](https://user-images.githubusercontent.com/3684879/191948877-41f7309c-612a-4a41-b860-e9e3953775d1.png)

The scripts for partition and TF extraction went fine. But when I start the PT script, it throws the following error. 

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/3684879/191948411-86664ca4-8fcc-47c2-8f81-3d3c37ddf092.png">

I will really appreciate if you have any suggestions, off the top of your head.

**Comment by lrasmy** [comment]
Hi Koustav Ghosal,

This error is probably due to the TensorFlow version and compatibility with your Cuda. This code version is mainly compatible with Tensorflow 1.15 or less.

you can follow the solution on https://developpaper.com/install-tensorflow-1-15-in-python-3-8-cuda-11-environment/

Thanks,
Laila
